export const onwinProducts = [
  [
    {
      name: 'Virgin Aperol Spritz',
      description: 'Безалкогольный битер, сок цитрусовый, содовая',
      price: 15,
      count: 1,
      image: require('../assets/virgin.png'),
    },
    {
      name: 'Ginger Ale',
      description: 'Корень имбиря, пряности, сок цитрусовых и мед',
      price: 15,
      count: 1,
      image: require('../assets/ginger.png'),
    },
    {
      name: 'Magic Lake',
      description: 'Персик, юзу, цвет бузины, тоник',
      price: 17,
      count: 1,
      image: require('../assets/magic.png'),
    },
    {
      name: 'Rosado Brut',
      description: 'Розовое игристое, Брют',
      price: 20,
      count: 1,
      image: require('../assets/rosado.png'),
    },
    {
      name: 'Pure Garden',
      description: 'Сироп цветов бузины, яблоко цитрус, имбирный эль',
      price: 19,
      count: 1,
      image: require('../assets/pure.png'),
    },
    {
      name: 'Фреш',
      description: 'Апельсин/грейпфрут/яблоко/морковь',
      price: 15,
      count: 1,
      image: require('../assets/fresh.png'),
    },
  ],
  [
    {
      name: 'Мини-Брускетты',
      description:
        'Хрустящие кусочки багета, покрытые оливковым маслом, томатами',
      price: 25,
      count: 1,
      image: require('../assets/mini_brus.png'),
    },
    {
      name: 'Грибные Капсулы',
      description: 'Шампиньоны, заполненные смесью сыра, чеснока и зелени',
      price: 22,
      count: 1,
      image: require('../assets/gribniye.png'),
    },
    {
      name: 'Сырные Шарики',
      description: 'Маленькие шарики из крем-сыра и тертого пармезана',
      price: 18,
      count: 1,
      image: require('../assets/sirniye.png'),
    },
    {
      name: 'Карпаччо из Свеклы',
      description:
        'Свекла, выложенная в виде карпаччо, с крошками козьего сыра',
      price: 26,
      count: 1,
      image: require('../assets/karpachcho.png'),
    },
    {
      name: 'Фалафель',
      description:
        'Домашний фалафель из нута и трав, подаваемый с кремовым соусом тахини',
      price: 30,
      count: 1,
      image: require('../assets/falafel.png'),
    },
    {
      name: 'Тарталетки',
      description:
        'Нежные тарталетки, наполненные смесью измельченных креветок',
      price: 21,
      count: 1,
      image: require('../assets/tartaletki.png'),
    },
  ],
  [
    {
      name: 'Соте из Гребешков',
      description: ' Нежные гребешки, обжаренные в чесночном масле',
      price: 18,
      count: 1,
      image: require('../assets/sote.png'),
    },
    {
      name: 'Креветки',
      description: 'Хрустящие креветки в кокосовой панировке',
      price: 25,
      count: 1,
      image: require('../assets/krevetki.png'),
    },
    {
      name: 'Тартар из Тунца',
      description: 'Свежий тунец, нарезанный кубиками, смешанный с авокадо',
      price: 19,
      count: 1,
      image: require('../assets/tartar.png'),
    },
    {
      name: 'Лингвини с Мидиями',
      description:
        'Мидии, приготовленные в ароматном томатном соусе с чесноком',
      price: 16,
      count: 1,
      image: require('../assets/lingvini.png'),
    },
    {
      name: 'Ризотто с Кальмарами',
      description: 'Кремовое ризотто с нежными кусочками кальмаров',
      price: 21,
      count: 1,
      image: require('../assets/rizotto.png'),
    },
    {
      name: 'Овощной Салат',
      description: 'Легкий салат из свежих овощей с кусочками копчёного лосося',
      price: 30,
      count: 1,
      image: require('../assets/ovoshnoy.png'),
    },
  ],
  [
    {
      name: 'Шоколадный Фондан',
      description: 'Нежный шоколадный фондан с текучей серединой',
      price: 36,
      count: 1,
      image: require('../assets/shokoladniy.png'),
    },
    {
      name: 'Тирамису',
      description: 'Слои нежного сыра маскарпоне, пропитанные ликёрным сиропом',
      price: 18,
      count: 1,
      image: require('../assets/tiramisu.png'),
    },
    {
      name: 'Чизкейк с Ягодами',
      description: 'Воздушный сливочно-сырный чизкейк на песочной основе',
      price: 15,
      count: 1,
      image: require('../assets/chizkeyk.png'),
    },
    {
      name: 'Панна Котта с Манго',
      description:
        'Кремовая панна котта с нотками ванили, подается с пюре из манго',
      price: 20,
      count: 1,
      image: require('../assets/panna.png'),
    },
    {
      name: 'Лавандовый Мусс',
      description:
        'Легкий лавандовый мусс с нежной текстурой, подается с крошкой',
      price: 24,
      count: 1,
      image: require('../assets/lavandoviy.png'),
    },
    {
      name: 'Кардамонный Рулет',
      description:
        ' Воздушное тесто с кардамоном, завернутое в апельсиновый крем',
      price: 17,
      count: 1,
      image: require('../assets/kardamonniy.png'),
    },
  ],
];

export const onwinProductsAll = [
  {
    name: 'Virgin Aperol Spritz',
    description: 'Безалкогольный битер, сок цитрусовый, содовая',
    price: 15,
    count: 1,
    image: require('../assets/virgin.png'),
  },
  {
    name: 'Ginger Ale',
    description: 'Корень имбиря, пряности, сок цитрусовых и мед',
    price: 15,
    count: 1,
    image: require('../assets/ginger.png'),
  },
  {
    name: 'Magic Lake',
    description: 'Персик, юзу, цвет бузины, тоник',
    price: 17,
    count: 1,
    image: require('../assets/magic.png'),
  },
  {
    name: 'Rosado Brut',
    description: 'Розовое игристое, Брют',
    price: 20,
    count: 1,
    image: require('../assets/rosado.png'),
  },
  {
    name: 'Pure Garden',
    description: 'Сироп цветов бузины, яблоко цитрус, имбирный эль',
    price: 19,
    count: 1,
    image: require('../assets/pure.png'),
  },
  {
    name: 'Фреш',
    description: 'Апельсин/грейпфрут/яблоко/морковь',
    price: 15,
    count: 1,
    image: require('../assets/fresh.png'),
  },
  {
    name: 'Мини-Брускетты',
    description:
      'Хрустящие кусочки багета, покрытые оливковым маслом, томатами',
    price: 25,
    count: 1,
    image: require('../assets/mini_brus.png'),
  },
  {
    name: 'Грибные Капсулы',
    description: 'Шампиньоны, заполненные смесью сыра, чеснока и зелени',
    price: 22,
    count: 1,
    image: require('../assets/gribniye.png'),
  },
  {
    name: 'Сырные Шарики',
    description: 'Маленькие шарики из крем-сыра и тертого пармезана',
    price: 18,
    count: 1,
    image: require('../assets/sirniye.png'),
  },
  {
    name: 'Карпаччо из Свеклы',
    description: 'Свекла, выложенная в виде карпаччо, с крошками козьего сыра',
    price: 26,
    count: 1,
    image: require('../assets/karpachcho.png'),
  },
  {
    name: 'Фалафель',
    description:
      'Домашний фалафель из нута и трав, подаваемый с кремовым соусом тахини',
    price: 30,
    count: 1,
    image: require('../assets/falafel.png'),
  },
  {
    name: 'Тарталетки',
    description: 'Нежные тарталетки, наполненные смесью измельченных креветок',
    price: 21,
    count: 1,
    image: require('../assets/tartaletki.png'),
  },
  {
    name: 'Соте из Гребешков',
    description: ' Нежные гребешки, обжаренные в чесночном масле',
    price: 18,
    count: 1,
    image: require('../assets/sote.png'),
  },
  {
    name: 'Креветки',
    description: 'Хрустящие креветки в кокосовой панировке',
    price: 25,
    count: 1,
    image: require('../assets/krevetki.png'),
  },
  {
    name: 'Тартар из Тунца',
    description: 'Свежий тунец, нарезанный кубиками, смешанный с авокадо',
    price: 19,
    count: 1,
    image: require('../assets/tartar.png'),
  },
  {
    name: 'Лингвини с Мидиями',
    description: 'Мидии, приготовленные в ароматном томатном соусе с чесноком',
    price: 16,
    count: 1,
    image: require('../assets/lingvini.png'),
  },
  {
    name: 'Ризотто с Кальмарами',
    description: 'Кремовое ризотто с нежными кусочками кальмаров',
    price: 21,
    count: 1,
    image: require('../assets/rizotto.png'),
  },
  {
    name: 'Овощной Салат',
    description: 'Легкий салат из свежих овощей с кусочками копчёного лосося',
    price: 30,
    count: 1,
    image: require('../assets/ovoshnoy.png'),
  },
  {
    name: 'Шоколадный Фондан',
    description: 'Нежный шоколадный фондан с текучей серединой',
    price: 36,
    count: 1,
    image: require('../assets/shokoladniy.png'),
  },
  {
    name: 'Тирамису',
    description: 'Слои нежного сыра маскарпоне, пропитанные ликёрным сиропом',
    price: 18,
    count: 1,
    image: require('../assets/tiramisu.png'),
  },
  {
    name: 'Чизкейк с Ягодами',
    description: 'Воздушный сливочно-сырный чизкейк на песочной основе',
    price: 15,
    count: 1,
    image: require('../assets/chizkeyk.png'),
  },
  {
    name: 'Панна Котта с Манго',
    description:
      'Кремовая панна котта с нотками ванили, подается с пюре из манго',
    price: 20,
    count: 1,
    image: require('../assets/panna.png'),
  },
  {
    name: 'Лавандовый Мусс',
    description:
      'Легкий лавандовый мусс с нежной текстурой, подается с крошкой',
    price: 24,
    count: 1,
    image: require('../assets/lavandoviy.png'),
  },
  {
    name: 'Кардамонный Рулет',
    description:
      ' Воздушное тесто с кардамоном, завернутое в апельсиновый крем',
    price: 17,
    count: 1,
    image: require('../assets/kardamonniy.png'),
  },
];
